export const NotifyConstant = {
  GET_ALL_NOTIFY_REQUEST: "GET_ALL_NOTIFY_REQUEST",
  GET_ALL_NOTIFY_SUCCESS: "GET_ALL_NOTIFY_SUCCESS",
  GET_ALL_NOTIFY_FAILED: "GET_ALL_NOTIFY_FAILED",

  GET_ALL_NOTIFY_TYPE_REQUEST: "GET_ALL_NOTIFY_TYPE_REQUEST",
  GET_ALL_NOTIFY_TYPE_SUCCESS: "GET_ALL_NOTIFY_TYPE_SUCCESS",
  GET_ALL_NOTIFY_TYPE_FAILED: "GET_ALL_NOTIFY_TYPE_FAILED",

  SEND_ALL_NOTIFY_REQUEST: "SEND_ALL_NOTIFY_REQUEST",
  SEND_ALL_NOTIFY_SUCCESS: "SEND_ALL_NOTIFY_SUCCESS",
  SEND_ALL_NOTIFY_FAILED: "SEND_ALL_NOTIFY_FAILED",

  SEND_NOTIFY_REQUEST: "SEND_NOTIFY_REQUEST",
  SEND_NOTIFY_SUCCESS: "SEND_NOTIFY_SUCCESS",
  SEND_NOTIFY_FAILED: "SEND_NOTIFY_FAILED",

  DELETE_NOTIFY_REQUEST: "DELETE_NOTIFY_REQUEST",
  DELETE_NOTIFY_SUCCESS: "DELETE_NOTIFY_SUCCESS",
  DELETE_NOTIFY_FAILED: "DELETE_NOTIFY_FAILED"
}
