export const SpecifyTestConstant = {
  GET_ALL_SPECIFY_TEST_REQUEST: "GET_ALL_SPECIFY_TEST_REQUEST",
  GET_ALL_SPECIFY_TEST_SUCCESS: "GET_ALL_SPECIFY_TEST_SUCCESS",
  GET_ALL_SPECIFY_TEST_FAILED: "GET_ALL_SPECIFY_TEST_FAILED",

  GET_DETAIL_SPECIFY_TEST_REQUEST: "GET_DETAIL_SPECIFY_TEST_REQUEST",
  GET_DETAIL_SPECIFY_TEST_SUCCESS: "GET_DETAIL_SPECIFY_TEST_SUCCESS",
  GET_DETAIL_SPECIFY_TEST_FAILED: "GET_DETAIL_SPECIFY_TEST_FAILED"
}
