export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  GET_CURRENT_USER_REQUEST: "GET_CURRENT_USER_REQUEST",
  GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_FAILURE: "GET_CURRENT_USER_FAILURE",

  CHANGE_INFO_REQUEST: "CHANGE_INFO_REQUEST",
  CHANGE_INFO_SUCCESS: "CHANGE_INFO_SUCCESS",
  CHANGE_INFO_FAILURE: "CHANGE_INFO_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILURE: "REFRESH_TOKEN_FAILURE",

  CANCEL_REQUEST: "CANCEL_REQUEST",

  IMPORT_USERS_REQUEST: "IMPORT_USERS_REQUEST",
  IMPORT_USERS_SUCCESS: "IMPORT_USERS_SUCCESS",
  IMPORT_USERS_FAILURE: "IMPORT_USERS_FAILURE",

  CHECK_TOKEN_EXPIRED: "CHECK_TOKEN_EXPIRED",

  LOGOUT_ALL_SESSION_REQUEST: "LOGOUT_ALL_SESSION_REQUEST",
  LOGOUT_ALL_SESSION_SUCCESS: "LOGOUT_ALL_SESSION_SUCCESS",
  LOGOUT_ALL_SESSION_FAILURE: "LOGOUT_ALL_SESSION_FAILURE",

  LOGOUT_ALL_USER_SESSION_REQUEST: "LOGOUT_ALL_USER_SESSION_REQUEST",
  LOGOUT_ALL_USER_SESSION_SUCCESS: "LOGOUT_ALL_USER_SESSION_SUCCESS",
  LOGOUT_ALL_USER_SESSION_FAILURE: "LOGOUT_ALL_USER_SESSION_FAILURE"
}
