export const FunctionConstant = {
  GET_ALL_FUNCTION_REQ: "GET_ALL_FUNCTION_REQ",
  GET_ALL_FUNCTION_SUC: "GET_ALL_FUNCTION_SUC",
  GET_ALL_FUNCTION_FAL: "GET_ALL_FUNCTION_FAL",

  GET_FUNC_DETAIL_REQ: "GET_FUNC_DETAIL_REQ",
  GET_FUNC_DETAIL_SUC: "GET_FUNC_DETAIL_SUC",
  GET_FUNC_DETAIL_FAL: "GET_FUNC_DETAIL_FAL",

  SAVE_FUNC_REQ: "SAVE_FUNC_REQ",
  SAVE_FUNC_SUC: "SAVE_FUNC_SUC",
  SAVE_FUNC_FAL: "SAVE_FUNC_FAL",

  UPDATE_FUNC_REQ: "UPDATE_FUNC_REQ",
  UPDATE_FUNC_SUC: "UPDATE_FUNC_SUC",
  UPDATE_FUNC_FAL: "UPDATE_FUNC_FAL",

  DELETE_FUNC_REQ: "DELETE_FUNC_REQ",
  DELETE_FUNC_SUC: "DELETE_FUNC_SUC",
  DELETE_FUNC_FAL: "DELETE_FUNC_FAL",

  FIND_ALL_FUNCTION_REQUEST: "FIND_ALL_FUNCTION_REQUEST",
  FIND_ALL_FUNCTION_SUCCESS: "FIND_ALL_FUNCTION_SUCCESS",
  FIND_ALL_FUNCTION_FAILURE: "FIND_ALL_FUNCTION_FAILURE",

  FIND_FUNCTION_BY_PARENT_ID_REQUEST: "FIND_FUNCTION_BY_PARENT_ID_REQUEST",
  FIND_FUNCTION_BY_PARENT_ID_SUCCESS: "FIND_FUNCTION_BY_PARENT_ID_SUCCESS",
  FIND_FUNCTION_BY_PARENT_ID_FAILURE: "FIND_FUNCTION_BY_PARENT_ID_FAILURE",

  FIND_FUNCTION_BY_FUNCTION_ROOT_REQUEST:
    "FIND_FUNCTION_BY_FUNCTION_ROOT_REQUEST",
  FIND_FUNCTION_BY_FUNCTION_ROOT_SUCCESS:
    "FIND_FUNCTION_BY_FUNCTION_ROOT_SUCCESS",
  FIND_FUNCTION_BY_FUNCTION_ROOT_FAILURE:
    "FIND_FUNCTION_BY_FUNCTION_ROOT_FAILURE"
}
