export const GroupFunctionConstants = {
  GET_ALL_GROUP_FUNCTION_REQUEST: "GET_ALL_GROUP_FUNCTION_REQUEST",
  GET_ALL_GROUP_FUNCTION_SUCCESS: "GET_ALL_GROUP_FUNCTION_SUCCESS",
  GET_ALL_GROUP_FUNCTION_FAILURE: "GET_ALL_GROUP_FUNCTION_FAILURE",

  GET_GROUP_FUNCTION_BY_ID_REQUEST: "GET_GROUP_FUNCTION_BY_ID_REQUEST",
  GET_GROUP_FUNCTION_BY_ID_SUCCESS: "GET_GROUP_FUNCTION_BY_ID_SUCCESS",
  GET_GROUP_FUNCTION_BY_ID_FAILURE: "GET_GROUP_FUNCTION_BY_ID_FAILURE",

  SAVE_GROUP_FUNCTION_REQUEST: "SAVE_GROUP_FUNCTION_REQUEST",
  SAVE_GROUP_FUNCTION_SUCCSESS: "SAVE_GROUP_FUNCTION_SUCCSESS",
  SAVE_GROUP_FUNCTION_FAILURE: "SAVE_GROUP_FUNCTION_FAILURE",

  UPDATE_GROUP_FUNCTION_REQUEST: "UPDATE_GROUP_FUNCTION_REQUEST",
  UPDATE_GROUP_FUNCTION_SUCCSESS: "UPDATE_GROUP_FUNCTION_SUCCSESS",
  UPDATE_GROUP_FUNCTION_FAILURE: "UPDATE_GROUP_FUNCTION_FAILURE",

  GET_GROUP_FUNCTION_BY_GROUP_IDs_REQUEST:
    "GET_GROUP_FUNCTION_BY_GROUP_IDs_REQUEST",
  GET_GROUP_FUNCTION_BY_GROUP_IDs_SUCCESS:
    "GET_GROUP_FUNCTION_BY_GROUP_IDs_SUCCESS",
  GET_GROUP_FUNCTION_BY_GROUP_IDs_FAILURE:
    "GET_GROUP_FUNCTION_BY_GROUP_IDs_FAILURE"
}
