export const GroupConstants = {
  GET_ALL_GROUP_REQUEST: "GET_ALL_GROUP_REQUEST",
  GET_ALL_GROUP_SUCCESS: "GET_ALL_GROUP_SUCCESS",
  GET_ALL_GROUP_FAILURE: "GET_ALL_GROUP_FAILURE",

  GET_GROUP_BY_ID_REQUEST: "GET_GROUP_BY_ID_REQUEST",
  GET_GROUP_BY_ID_SUCCESS: "GET_GROUP_BY_ID_SUCCESS",
  GET_GROUP_BY_ID_FAILURE: "GET_GROUP_BY_ID_FAILURE",

  SAVE_GROUP_REQUEST: "SAVE_GROUP_REQUEST",
  SAVE_GROUP_SUCCSESS: "SAVE_GROUP_SUCCSESS",
  SAVE_GROUP_FAILURE: "SAVE_GROUP_FAILURE",

  UPDATE_GROUP_REQUEST: "UPDATE_GROUP_REQUEST",
  UPDATE_GROUP_SUCCSESS: "UPDATE_GROUP_SUCCSESS",
  UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",

  REMOVE_GROUP_REQUEST: "REMOVE_GROUP_REQUEST",
  REMOVE_GROUP_SUCCSESS: "REMOVE_GROUP_SUCCSESS",
  REMOVE_GROUP_FAILURE: "REMOVE_GROUP_FAILURE",

  FIND_ALL_GROUP_REQUEST: "FIND_ALL_GROUP_REQUEST",
  FIND_ALL_GROUP_SUCCESS: "FIND_ALL_GROUP_SUCCESS",
  FIND_ALL_GROUP_FAILURE: "FIND_ALL_GROUP_FAILURE"
}
