export const AccountConstant = {
  GET_ALL_ACCOUNT_REQUEST: "GET_ALL_ACCOUNT_REQUEST",
  GET_ALL_ACCOUNT_SUCCESS: "GET_ALL_ACCOUNT_SUCCESS",
  GET_ALL_ACCOUNT_FAILURE: "GET_ALL_ACCOUNT_FAILURE",

  GET_DETAIL_ACCOUNT_REQUEST: "GET_DETAIL_ACCOUNT_REQUEST",
  GET_DETAIL_ACCOUNT_SUCCESS: "GET_DETAIL_ACCOUNT_SUCCESS",
  GET_DETAIL_ACCOUNT_FAILURE: "GET_DETAIL_ACCOUNT_FAILURE",

  SAVE_ACCOUNT_REQUEST: "SAVE_ACCOUNT_REQUEST",
  SAVE_ACCOUNT_SUCCESS: "SAVE_ACCOUNT_SUCCESS",
  SAVE_ACCOUNT_FAILURE: "SAVE_ACCOUNT_FAILURE",

  UPDATE_ACCOUNT_REQUEST: "UPDATE_ACCOUNT_REQUEST",
  UPDATE_ACCOUNT_SUCCESS: "UPDATE_ACCOUNT_SUCCESS",
  UPDATE_ACCOUNT_FAILURE: "UPDATE_ACCOUNT_FAILURE",

  REMOVE_ACCOUNT_REQUEST: "REMOVE_ACCOUNT_REQUEST",
  REMOVE_ACCOUNT_SUCCESS: "REMOVE_ACCOUNT_SUCCESS",
  REMOVE_ACCOUNT_FAILURE: "REMOVE_ACCOUNT_FAILURE",

  REMOVE_PERMANENTLY_ACCOUNT_REQUEST: "REMOVE_PERMANENTLY_ACCOUNT_REQUEST",
  REMOVE_PERMANENTLY_ACCOUNT_SUCCESS: "REMOVE_PERMANENTLY_ACCOUNT_SUCCESS",
  REMOVE_PERMANENTLY_ACCOUNT_FAILURE: "REMOVE_PERMANENTLY_ACCOUNT_FAILURE",

  SAVE_PERMISSION_REQUEST: "SAVE_PERMISSION_REQUEST",
  SAVE_PERMISSION_SUCCESS: "SAVE_PERMISSION_SUCCESS",
  SAVE_PERMISSION_FAILURE: "SAVE_PERMISSION_FAILURE",

  FIND_ALL_ACCOUNT_REQUEST: "FIND_ALL_ACCOUNT_REQUEST",
  FIND_ALL_ACCOUNT_SUCCESS: "FIND_ALL_ACCOUNT_SUCCESS",
  FIND_ALL_ACCOUNT_FAILURE: "FIND_ALL_ACCOUNT_FAILURE",

  UPDATE_USER_FACILITY_REQUEST: "UPDATE_USER_FACILITY_REQUEST",
  UPDATE_USER_FACILITY_SUCCESS: "UPDATE_USER_FACILITY_SUCCESS",
  UPDATE_USER_FACILITY_FAILURE: "UPDATE_USER_FACILITY_FAILURE",

  GET_USER_FACILITY_REQUEST: "GET_USER_FACILITY_REQUEST",
  GET_USER_FACILITY_SUCCESS: "GET_USER_FACILITY_SUCCESS",
  GET_USER_FACILITY_FAILURE: "GET_USER_FACILITY_FAILURE"
}
