export const ParamConstant = {
  GET_ALL_PARAM_REQUEST: "GET_ALL_PARAM_REQUEST",
  GET_ALL_PARAM_SUCCESS: "GET_ALL_PARAM_SUCCESS",
  GET_ALL_PARAM_FAILURE: "GET_ALL_PARAM_FAILURE",

  SAVE_PARAM_REQUEST: "SAVE_PARAM_REQUEST",
  SAVE_PARAM_SUCCESS: "SAVE_PARAM_SUCCESS",
  SAVE_PARAM_FAILURE: "SAVE_PARAM_FAILURE",

  UPDATE_PARAM_REQUEST: "UPDATE_PARAM_REQUEST",
  UPDATE_PARAM_SUCCESS: "UPDATE_PARAM_SUCCESS",
  UPDATE_PARAM_FAILURE: "UPDATE_PARAM_FAILURE",

  DELETE_PARAM_REQUEST: "DELETE_PARAM_REQUEST",
  DELETE_PARAM_SUCCESS: "DELETE_PARAM_SUCCESS",
  DELETE_PARAM_FAILURE: "DELETE_PARAM_FAILURE",

  FIND_ALL_PARAM_REQUEST: "FIND_ALL_PARAM_REQUEST",
  FIND_ALL_PARAM_SUCCESS: "FIND_ALL_PARAM_SUCCESS",
  FIND_ALL_PARAM_FAILURE: "FIND_ALL_PARAM_FAILURE"
}
