export const UserTypeConstant = {
  GET_ALL_USER_TYPE_REQUEST: "GET_ALL_USER_TYPE_REQUEST",
  GET_ALL_USER_TYPE_SUCCESS: "GET_ALL_USER_TYPE_SUCCESS",
  GET_ALL_USER_TYPE_FAILURE: "GET_ALL_USER_TYPE_FAILURE",

  SAVE_USER_TYPE_REQUEST: "SAVE_USER_TYPE_REQUEST",
  SAVE_USER_TYPE_SUCCESS: "SAVE_USER_TYPE_SUCCESS",
  SAVE_USER_TYPE_FAILURE: "SAVE_USER_TYPE_FAILURE",

  UPDATE_USER_TYPE_REQUEST: "UPDATE_USER_TYPE_REQUEST",
  UPDATE_USER_TYPE_SUCCESS: "UPDATE_USER_TYPE_SUCCESS",
  UPDATE_USER_TYPE_FAILURE: "UPDATE_USER_TYPE_FAILURE",

  DELETE_USER_TYPE_REQUEST: "DELETE_USER_TYPE_REQUEST",
  DELETE_USER_TYPE_SUCCESS: "DELETE_USER_TYPE_SUCCESS",
  DELETE_USER_TYPE_FAILURE: "DELETE_USER_TYPE_FAILURE",

  DELETE_PERMANENTLY_USER_TYPE_REQUEST: "DELETE_USER_TYPE_REQUEST",
  DELETE_PERMANENTLY_USER_TYPE_SUCCESS: "DELETE_USER_TYPE_SUCCESS",
  DELETE_PERMANENTLY_USER_TYPE_FAILURE: "DELETE_USER_TYPE_FAILURE",

  FIND_ALL_USER_TYPE_REQUEST: "FIND_ALL_USER_TYPE_REQUEST",
  FIND_ALL_USER_TYPE_SUCCESS: "FIND_ALL_USER_TYPE_SUCCESS",
  FIND_ALL_USER_TYPE_FAILURE: "FIND_ALL_USER_TYPE_FAILURE"
}
